const test=require('node:test');
const assert=require('node:assert/strict');
const {CONFIG,analyze}=require('./fundamental-score');

test('Fundamental Score excelente combina dimensões configuradas',()=>{const result=analyze({metrics:{roic:22,earningsCagr:15,netDebtToEbitda:.8,priceEarnings:7},incomeHistory:[{netIncome:1},{netIncome:1},{netIncome:1},{netIncome:1},{netIncome:1}],dividendYears:5});assert.equal(result.score,10);assert.equal(result.classification,'EXCELENTE');assert.equal(result.positiveYears,5);assert.ok(result.highlights.some(item=>item[1]==='Alta eficiência na alocação de capital'))});
test('Fundamental Score repondera dados ausentes em vez de tratá-los como zero',()=>{const result=analyze({metrics:{roe:20},incomeHistory:[]});assert.equal(result.dimensions.profitability,10);assert.equal(result.dimensions.debt,null);assert.equal(result.score,10);assert.equal(result.classification,'EXCELENTE')});
test('Fundamental Score trata dataset completamente ausente sem NaN ou exceção',()=>{const result=analyze({metrics:{},incomeHistory:[]});assert.equal(result.score,0);assert.equal(result.classification,'RUIM');assert.equal(result.takeaway,'Fundamentos frágeis: a qualidade fundamental reduz o Edge da oportunidade.')});
test('Histórico de lucros usa somente anos positivos e dívida alta cria alerta determinístico',()=>{const result=analyze({metrics:{roe:12,netDebtToEbitda:3.5},incomeHistory:[{netIncome:10},{netIncome:0},{netIncome:-1},{netIncome:8}]});assert.equal(result.positiveYears,2);assert.equal(result.yearsCount,4);assert.ok(result.highlights.some(item=>item[0]==='warn'&&item[1]==='Endividamento elevado'))});
test('Configuração expõe pesos e faixas calibráveis',()=>{assert.deepEqual(Object.keys(CONFIG.weights),['profitability','consistency','growth','debt','valuation','dividends']);assert.equal(CONFIG.classes[0][0],'EXCELENTE');assert.equal(CONFIG.classes.at(-1)[0],'RUIM')});
