(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.TradingRubrics=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const DEFAULT_POLICY={
    criteria:[
      {key:'marketCycle',label:'Market Cycle · permissão de mercado',weight:4},
      {key:'trendQuality',label:'Diário / Contexto técnico',weight:1.5},
      {key:'relativeStrength',label:'RS Rank / Força Relativa',weight:1.5},
      {key:'setupQuality',label:'Setup / Contração 4H',weight:1},
      {key:'volatility',label:'ATR% adequado',weight:.75},
      {key:'entryQuality',label:'Price Action fluido',weight:.75},
      {key:'fundamentalScore',label:'Fundamentalista',weight:.5}
    ],
    ratingScale:{bad:{label:'Ruim',score:0},medium:{label:'Médio',score:.5},good:{label:'Bom',score:1},healthy:{label:'Saudável',score:1},improving:{label:'Melhorando',score:.75},transition:{label:'Transição',score:.5},defensive:{label:'Defensivo',score:.25},riskOff:{label:'Risk-Off',score:0}},
    grades:[{grade:'A+',minScore:8.5,riskPct:.004},{grade:'B',minScore:7,riskPct:.002},{grade:'C',minScore:5.5,riskPct:.001},{grade:'No Trade',minScore:-Infinity,riskPct:0}],
    marketMultipliers:{healthy:1,improving:.75,transition:.5,defensive:.25,riskOff:0},
    profiles:{
      rampUp:{label:'Risk Ramp-Up · mercado em recuperação',initialRiskPct:.001,ongoingRiskPct:.0025,initialVolatilityPct:.001,ongoingVolatilityPct:.0025,capitalPct:.1,maximumPortfolioRiskPct:.05,maximumPositions:3,pyramiding:false},
      standard:{label:'Política padrão · mercado saudável',initialRiskPct:.003,ongoingRiskPct:.006,initialVolatilityPct:.003,ongoingVolatilityPct:.006,capitalPct:.1,maximumPortfolioRiskPct:.05,maximumPositions:6,pyramiding:false}
    },
    selectedProfile:'standard'
  };
  const finite=(value,fallback)=>Number.isFinite(Number(value))?Number(value):fallback;
  function normalizePolicy(policy={}){
    const savedCriteria=Array.isArray(policy.criteria)?policy.criteria:[];
    const criteria=DEFAULT_POLICY.criteria.map(base=>{const saved=savedCriteria.find(item=>item.key===base.key||(base.key==='fundamentalScore'&&item.key==='sector'))||{};return{...base,weight:Math.max(0,finite(saved.weight,base.weight))}});
    const grades=(Array.isArray(policy.grades)?policy.grades:DEFAULT_POLICY.grades).filter(item=>item.grade!=='A').map(item=>({...item,minScore:item.grade==='No Trade'?-Infinity:finite(item.minScore,0),riskPct:Math.max(0,finite(item.riskPct,0))})).sort((a,b)=>b.minScore-a.minScore);
    const normalizedGrades=grades.some(item=>item.grade==='No Trade')?grades:[...grades,{grade:'No Trade',minScore:-Infinity,riskPct:0}];
    const multipliers={...DEFAULT_POLICY.marketMultipliers,...(policy.marketMultipliers||{})};Object.keys(DEFAULT_POLICY.marketMultipliers).forEach(key=>multipliers[key]=Math.max(0,finite(multipliers[key],DEFAULT_POLICY.marketMultipliers[key])));
    const profiles={};Object.entries(DEFAULT_POLICY.profiles).forEach(([key,base])=>{const saved=policy.profiles?.[key]||{};profiles[key]={...base,...saved,initialRiskPct:Math.max(0,finite(saved.initialRiskPct,base.initialRiskPct)),ongoingRiskPct:Math.max(0,finite(saved.ongoingRiskPct,base.ongoingRiskPct)),initialVolatilityPct:Math.max(0,finite(saved.initialVolatilityPct,base.initialVolatilityPct)),ongoingVolatilityPct:Math.max(0,finite(saved.ongoingVolatilityPct,base.ongoingVolatilityPct)),capitalPct:Math.max(0,finite(saved.capitalPct,base.capitalPct)),maximumPortfolioRiskPct:Math.max(0,finite(saved.maximumPortfolioRiskPct,base.maximumPortfolioRiskPct)),maximumPositions:Math.max(1,Math.floor(finite(saved.maximumPositions,base.maximumPositions))),pyramiding:false}});
    const selectedProfile=profiles[policy.selectedProfile]?policy.selectedProfile:DEFAULT_POLICY.selectedProfile;
    return{criteria,ratingScale:{...DEFAULT_POLICY.ratingScale,...(policy.ratingScale||{})},grades:normalizedGrades,marketMultipliers:multipliers,profiles,selectedProfile};
  }
  function profileFor(policy={},profileKey){const normalized=normalizePolicy(policy),key=profileKey&&normalized.profiles[profileKey]?profileKey:normalized.selectedProfile;return{key,...normalized.profiles[key]}}
  function marketCycleKey(value){const normalized=String(value||'').toLowerCase();if(['healthy','saudável','saudavel','risk-on','up'].includes(normalized))return'healthy';if(['improving','melhorando'].includes(normalized))return'improving';if(['transition','transição','transicao','neutral','neutro'].includes(normalized))return'transition';if(['defensive','defensivo','weak','sideways','deteriorating','desfavorável','desfavoravel'].includes(normalized))return'defensive';if(['riskoff','risk-off','doente','down'].includes(normalized))return'riskOff';return'transition'}
  function calculateRubric(input={},policy){const p=normalizePolicy(policy),ratings=input.ratings||{},profile=profileFor(p,input.profileKey),derivedCycle=profile.key==='standard'?'healthy':'improving',hasRatingInput=Object.keys(ratings).length>0||p.criteria.some(c=>Boolean(input[c.key+'Rating']));const contributions=p.criteria.map(c=>{const selectedRating=ratings[c.key]||input[c.key+'Rating']||(c.key==='marketCycle'?derivedCycle:null);const raw=selectedRating&&p.ratingScale[selectedRating]?p.ratingScale[selectedRating].score:input[c.key];const value=Math.max(0,Math.min(1,finite(raw,0)));return{key:c.key,label:c.label,selectedRating,value,weight:c.weight,points:value*c.weight}});const complete=!hasRatingInput||p.criteria.every(c=>c.key==='marketCycle'||Boolean(ratings[c.key]||input[c.key+'Rating']));const score=contributions.reduce((sum,item)=>sum+item.points,0),grade=complete?(p.grades.find(item=>score>=item.minScore)||p.grades[p.grades.length-1]):{grade:'—',riskPct:0};const cycleKey=marketCycleKey(input.marketCycleRegime||input.marketCycle||derivedCycle),gradeRiskPct=grade.riskPct,profileCapPct=profile.initialRiskPct,marketFactor=1,finalRiskPct=Math.min(gradeRiskPct,profileCapPct);return{score,maximumScore:p.criteria.reduce((sum,item)=>sum+item.weight,0),grade:grade.grade,riskPct:finalRiskPct,gradeRiskPct,profileCapPct,marketFactor,marketCycle:cycleKey,profile,complete,contributions}}
  function riskBaseOptions(policy={}){return [...new Set(normalizePolicy(policy).grades.map(item=>item.riskPct).filter(Number.isFinite))].sort((a,b)=>a-b)}
  function calculatePositionSizing({equity,entry,stop,atr,riskPct,volatilityPct,capitalPct,lot=100}){const distance=Math.abs(Number(entry)-Number(stop));if(!(equity>0&&entry>0&&atr>0&&distance>0))return{quantity:0,layers:[],limitingLayer:null,initialRisk:0};const round=q=>Math.max(0,Math.floor(q/lot)*lot),layers=[{key:'risk',name:'Risco pelo stop',quantity:round(equity*riskPct/distance)},{key:'volatility',name:'Volatilidade / ATR',quantity:round(equity*volatilityPct/atr)},{key:'capital',name:'Limite de capital',quantity:round(equity*capitalPct/entry)}],limitingLayer=layers.reduce((a,b)=>b.quantity<a.quantity?b:a);return{quantity:limitingLayer.quantity,layers,limitingLayer:limitingLayer.key,initialRisk:limitingLayer.quantity*distance}}
  function calculateOngoingRisk({currentPrice,currentStop,quantity,direction='long',equity}){const sign=direction==='short'?-1:1,cash=Math.max(0,(Number(currentPrice)-Number(currentStop))*sign*Number(quantity));return{cash,riskPct:equity?cash/equity*100:0}}
  function calculatePeelOff({currentPrice,currentStop,atr,quantity,direction='long',equity,policy,profileKey,lot=100}){const profile=profileFor(policy,profileKey),sign=direction==='short'?-1:1,gap=Math.max(0,(Number(currentPrice)-Number(currentStop))*sign),current=Math.max(0,Number(quantity)||0),round=q=>Math.max(0,Math.floor(q/lot)*lot),byRisk=gap?round(Number(equity)*profile.ongoingRiskPct/gap):current,byVolatility=Number(atr)>0?round(Number(equity)*profile.ongoingVolatilityPct/Number(atr)):current,allowed=Math.min(current,byRisk,byVolatility),peel=Math.max(0,current-allowed);return{profile,allowedQuantity:allowed,peelQuantity:peel,required:peel>0,ongoingRiskPct:gap&&equity?gap*current/equity:0,ongoingVolatilityPct:atr&&equity?Number(atr)*current/equity:0,reason:byRisk<=byVolatility?'Risco em andamento':'Volatilidade em andamento'}}
  function validatePortfolio({currentHeatPct=0,additionalRiskPct=0,openPositions=0,maximumHeatPct=12.5,maximumPositions=10}){const projectedHeatPct=Number(currentHeatPct)+Number(additionalRiskPct),projectedPositions=Number(openPositions)+1,heatAllowed=projectedHeatPct<=Number(maximumHeatPct),positionsAllowed=projectedPositions<=Number(maximumPositions);return{projectedHeatPct,projectedPositions,heatAllowed,positionsAllowed,allowed:heatAllowed&&positionsAllowed}}
  return{DEFAULT_POLICY,normalizePolicy,profileFor,marketCycleKey,riskBaseOptions,calculateRubric,calculatePositionSizing,calculateOngoingRisk,calculatePeelOff,validatePortfolio};
});
