const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const {auditRecord,validateWisdomText}=require('../frontend/wisdom-text');
const root=path.resolve(__dirname,'..');
const read=file=>fs.readFileSync(path.join(root,file),'utf8');
const paths=JSON.parse(read('assets/wisdom-index.json')).items;
const context={window:{}};vm.runInNewContext(read('frontend/trader-wisdom-search-index.js'),context);
const ocr=context.window.traderWisdomSearchText;
const editorial=JSON.parse(read('assets/wisdom-editorial.json'));
const records=paths.map((image,index)=>{
 const data=editorial[image]||{};
 return auditRecord({...data,id:data.id||image,image,index,number:image.match(/tw-(\d+)/)[1],originalText:ocr[image]||''});
});
for(const record of records.filter(r=>!r.needsReview)){
 for(const field of ['quote','pt','author','title','source',...[]]){
  if(record[field]&&!validateWisdomText(record[field],{verified:true,kind:field==='source'?'source':'message'}).valid)throw Error(`Second-pass validation failed: ${record.id}/${field}`);
 }
}
const counts={total:records.length,valid:records.filter(r=>!r.needsReview).length,automaticallyCorrected:records.filter(r=>r.normalized.length&&!r.needsReview).length,normalized:records.filter(r=>r.normalized.length||r.searchText!==ocr[r.image]).length,translationCorrected:0,translationFallback:records.filter(r=>r.translationFallback).length,needsReview:records.filter(r=>r.needsReview).length,unrecoverable:records.filter(r=>r.unrecoverable).length};
const audit={version:3,counts,policy:'Only verified editorial transcriptions are publishable. Syntactically clean OCR still requires source review; raw originals are retained.',records:records.map(r=>({...r,before:{...(editorial[r.image]||{}),originalText:ocr[r.image]||''},after:{quote:r.quote,pt:r.pt,author:r.author,tags:r.tags,theme:r.theme}}))};
fs.mkdirSync(path.join(root,'docs/wisdom-audit'),{recursive:true});
fs.writeFileSync(path.join(root,'docs/wisdom-audit/audit.json'),JSON.stringify(audit,null,2));
fs.writeFileSync(path.join(root,'frontend/wisdom-catalog.js'),`/* Generated by scripts/audit-wisdom.cjs. Never edit raw OCR into approved messages. */\nwindow.wisdomCatalog=${JSON.stringify({counts,records})};\n`);
fs.writeFileSync(path.join(root,'docs/wisdom-audit/README.md'),`# Auditoria integral da Sabedoria do Trader V3\n\n${Object.entries(counts).map(([key,value])=>`- ${key}: ${value}`).join('\n')}\n\nTodos os ${counts.total} registros foram analisados; cada registro inclui original, antes/depois, motivos e status em audit.json. Uma segunda validação verificou todos os campos publicáveis.\n\nA leitura automática não comprova significado nem autoria. Mensagens sem transcrição editorial verificada permanecem em revisão, mesmo quando não contêm símbolos estranhos. Nenhum original foi apagado. A interface permite consultar esses originais sem publicar OCR como citação.\n\nNenhuma tradução automática foi inventada. Traduções válidas existentes foram preservadas; traduções suspeitas usam o original aprovado. A ausência de texto recuperável é um subconjunto dos pendentes e não significa perda do arquivo original. Contagens de normalização/correção podem se sobrepor.\n\nPara revisar: conferir a imagem, atualizar assets/wisdom-editorial.json e executar node scripts/audit-wisdom.cjs.\n`);
console.log(counts);
